// Generated by GraphWalker (http://www.graphwalker.org)
package interfaces;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "PetClinic/PetClinic.json")
public interface PetClinic {

    @Vertex()
    void v_FindOwners();

    @Edge()
    void e_HomePage();

    @Edge()
    void e_StartBrowser();

    @Edge()
    void e_Veterinarians();

    @Vertex()
    void v_Veterinarians();

    @Edge()
    void e_FindOwners();

    @Vertex()
    void v_HomePage();
}
